version: '3.4'

services:
    addressservice.api:
        image: ${DOCKER_REGISTRY-}addressserviceapi
        container_name: addressservice.api
        build:
            context: .
            dockerfile: AddressService.API/Dockerfile
        ports:
            - "5010:5010"
            - "5011:5011"

    address-db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: scoobydoo123!
          MSSQL_PID: Developer
        ports:
          - "1433:1433"
        volumes:
          - ./data:/var/opt/mssql/data